"""
rfis.pdf
~~~~~~~~~
Generates a formal, print-ready PDF for a single RFI using ReportLab Platypus.

Layout
------
  Header bar  — "REQUEST FOR INFORMATION" + RFI number
  Project     — name, number, manager, trade
  RFI Details — status, received, due, responded dates
  Parties     — designers / contract administrators
  Question    — full text
  Proposed Solution  (if present)
  Official Response  (if present) + responded-by / date
  Attachments list   (if any)
  Footer      — "Generated by RFI Filer  |  <date>  |  Page N"

Usage
-----
  from rfis.pdf import build_rfi_pdf
  buf = build_rfi_pdf(rfi_instance)   # returns io.BytesIO
"""

from __future__ import annotations

import io
from datetime import date, datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import KeepTogether

# ── Brand colours (matches the React app's indigo/blue palette) ──────────────
NAVY      = colors.HexColor("#1e3a5f")   # blue-950 equivalent  — header bg
INDIGO    = colors.HexColor("#4338ca")   # indigo-700           — section labels
SLATE_BG  = colors.HexColor("#f1f5f9")   # slate-100            — table zebra
WHITE     = colors.white
GRAY_TEXT = colors.HexColor("#6b7280")   # gray-500             — meta text
DARK_TEXT = colors.HexColor("#111827")   # gray-900             — body text
GREEN_BG  = colors.HexColor("#d1fae5")   # emerald-100          — response bg
AMBER_BG  = colors.HexColor("#fef3c7")   # amber-100            — open status
# ─────────────────────────────────────────────────────────────────────────────

TRADE_LABELS: dict[str, str] = {
    "M": "Mechanical",
    "E": "Electrical",
    "C": "Civil",
    "S": "Structural",
    "P": "Architectural",
}

PRIORITY_LABELS: dict[str, str] = {
    "low":      "Low",
    "medium":   "Medium",
    "high":     "High",
    "critical": "Critical",
}


def _fmt_date(value) -> str:
    """Format a date / datetime / None to a readable string."""
    if value is None:
        return "—"
    if isinstance(value, datetime):
        return value.strftime("%B %d, %Y")
    if isinstance(value, date):
        return value.strftime("%B %d, %Y")
    return str(value)


def _names(member_qs) -> str:
    """Turn a queryset of Members into a comma-separated name string."""
    names = [m.name for m in member_qs.all()]
    return ", ".join(names) if names else "—"


def _section_header(text: str, styles) -> list:
    """Return a labelled section header + rule as a flowable list."""
    return [
        Spacer(1, 0.18 * inch),
        Paragraph(text, styles["section_label"]),
        HRFlowable(
            width="100%",
            thickness=0.75,
            color=INDIGO,
            spaceAfter=6,
        ),
    ]


def _body_para(text: str, styles) -> Paragraph:
    """Wrap body text in a Paragraph, preserving newlines."""
    # Replace newlines with <br/> so ReportLab renders them correctly
    safe = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    safe = safe.replace("\n", "<br/>")
    return Paragraph(safe, styles["body"])


# ── Page footer callback ──────────────────────────────────────────────────────

def _make_footer(generated_on: str, app_url: Optional[str] = None):
    """Return an onPage callback that draws the footer on every page.

    If *app_url* is provided a clickable "View in RFI Filer →" hyperlink is
    drawn in the centre of the footer so recipients can jump straight to the
    live RFI record.
    """

    def _footer(canvas, doc):
        canvas.saveState()
        w, h = LETTER

        # Thin rule above footer
        canvas.setStrokeColor(colors.HexColor("#e2e8f0"))
        canvas.setLineWidth(0.5)
        canvas.line(0.75 * inch, 0.58 * inch, w - 0.75 * inch, 0.58 * inch)

        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(GRAY_TEXT)

        left_text  = f"Generated by RFI Filer  ·  {generated_on}"
        right_text = f"Page {doc.page}"

        canvas.drawString(0.75 * inch, 0.45 * inch, left_text)
        canvas.drawRightString(w - 0.75 * inch, 0.45 * inch, right_text)

        # Optional deep-link to the live RFI in the web app
        if app_url:
            link_text = "View in RFI Filer →"
            font_size = 7
            canvas.setFont("Helvetica-Bold", font_size)
            canvas.setFillColor(INDIGO)
            cx = w / 2
            canvas.drawCentredString(cx, 0.45 * inch, link_text)
            # Build a clickable rect around the text
            text_w = canvas.stringWidth(link_text, "Helvetica-Bold", font_size)
            canvas.linkURL(
                app_url,
                (cx - text_w / 2 - 2, 0.38 * inch, cx + text_w / 2 + 2, 0.56 * inch),
                relative=0,
            )

        canvas.restoreState()

    return _footer


# ── Main entry point ─────────────────────────────────────────────────────────

def build_rfi_pdf(
    rfi,
    *,
    app_url: Optional[str] = None,
    attachment_urls: Optional[dict] = None,
) -> io.BytesIO:
    """
    Generate a PDF for *rfi* (an ``rfis.models.Rfi`` instance).
    Returns an ``io.BytesIO`` buffer positioned at offset 0.

    Parameters
    ----------
    rfi:
        The ``Rfi`` model instance.  ``project``, ``designers``,
        ``contract_administrators``, ``responded_by`` and ``attachments``
        must already be prefetched / select_related before calling.
    app_url:
        Optional deep-link back to this RFI in the web app (e.g.
        ``https://app.example.com/rfi/42/p-001-rfi-001-roof-drainage``).
        When supplied, a clickable "View in RFI Filer →" hyperlink is
        rendered in the PDF footer on every page.
    attachment_urls:
        Optional mapping of ``{attachment_id: absolute_url}`` for the
        RFI's attachments.  When supplied, each entry in the Attachments
        section becomes a clickable hyperlink that opens the source file.
    """
    buf = io.BytesIO()
    generated_on = datetime.now().strftime("%B %d, %Y  %H:%M")

    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.85 * inch,   # room for footer
        title=f"{rfi.rfi_number} – {rfi.rfi_name}",
        author="RFI Filer",
    )

    # ── Styles ────────────────────────────────────────────────────────────────
    base = getSampleStyleSheet()

    styles: dict[str, ParagraphStyle] = {
        "doc_title": ParagraphStyle(
            "doc_title",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=WHITE,
            leading=13,
            alignment=TA_LEFT,
        ),
        "rfi_number_header": ParagraphStyle(
            "rfi_number_header",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=WHITE,
            leading=18,
            alignment=TA_RIGHT,
        ),
        "section_label": ParagraphStyle(
            "section_label",
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=INDIGO,
            leading=10,
            spaceAfter=2,
            spaceBefore=4,
        ),
        "table_label": ParagraphStyle(
            "table_label",
            fontName="Helvetica",
            fontSize=7.5,
            textColor=GRAY_TEXT,
            leading=10,
        ),
        "table_value": ParagraphStyle(
            "table_value",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            textColor=DARK_TEXT,
            leading=12,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=9,
            textColor=DARK_TEXT,
            leading=14,
            spaceAfter=4,
        ),
        "body_italic": ParagraphStyle(
            "body_italic",
            fontName="Helvetica-Oblique",
            fontSize=8.5,
            textColor=GRAY_TEXT,
            leading=13,
        ),
        "attachment_item": ParagraphStyle(
            "attachment_item",
            fontName="Helvetica",
            fontSize=8.5,
            textColor=DARK_TEXT,
            leading=13,
            leftIndent=10,
        ),
        "attachment_link": ParagraphStyle(
            "attachment_link",
            fontName="Helvetica",
            fontSize=8.5,
            textColor=INDIGO,
            leading=13,
            leftIndent=10,
        ),
        "response_meta": ParagraphStyle(
            "response_meta",
            fontName="Helvetica-Oblique",
            fontSize=8,
            textColor=GRAY_TEXT,
            leading=11,
            alignment=TA_RIGHT,
        ),
    }

    story = []

    # ── ① Header bar ─────────────────────────────────────────────────────────
    header_data = [[
        Paragraph("REQUEST FOR INFORMATION", styles["doc_title"]),
        Paragraph(rfi.rfi_number, styles["rfi_number_header"]),
    ]]
    header_table = Table(
        header_data,
        colWidths=["60%", "40%"],
        rowHeights=[0.55 * inch],
    )
    header_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), NAVY),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",  (0, 0), (0, -1),  12),
        ("RIGHTPADDING", (-1, 0), (-1, -1), 12),
        ("TOPPADDING",   (0, 0), (-1, -1),  8),
        ("BOTTOMPADDING",(0, 0), (-1, -1),  8),
        ("ROUNDEDCORNERS", [4]),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 0.08 * inch))

    # ── ② Sub-header — project name and RFI name ──────────────────────────
    sub_data = [[
        Paragraph(
            f"<b>{rfi.rfi_name}</b>",
            ParagraphStyle("sub_name", fontName="Helvetica-Bold",
                           fontSize=11, textColor=NAVY, leading=15),
        ),
        Paragraph(
            f"{rfi.project.project_number}  ·  {rfi.project.project_name}",
            ParagraphStyle("sub_proj", fontName="Helvetica",
                           fontSize=8.5, textColor=GRAY_TEXT, leading=12,
                           alignment=TA_RIGHT),
        ),
    ]]
    sub_table = Table(sub_data, colWidths=["55%", "45%"])
    sub_table.setStyle(TableStyle([
        ("VALIGN",      (0, 0), (-1, -1), "BOTTOM"),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
    ]))
    story.append(sub_table)

    # ── ③ Project & RFI details grid ─────────────────────────────────────────
    story += _section_header("PROJECT & RFI DETAILS", styles)

    trade_label    = TRADE_LABELS.get(rfi.trade, rfi.trade or "—")
    status_label   = "Closed" if rfi.status == "closed" else "Open"
    priority_label = PRIORITY_LABELS.get(getattr(rfi, "priority", "medium"), "Medium")

    def cell(label: str, value: str):
        return [
            Paragraph(label, styles["table_label"]),
            Paragraph(value or "—", styles["table_value"]),
        ]

    # 4 pairs × 2 columns = 8 sub-columns
    details_data = [
        [
            *cell("PROJECT NUMBER",  rfi.project.project_number),
            *cell("STATUS",          status_label),
            *cell("PRIORITY",        priority_label),
            *cell("TRADE",           trade_label),
        ],
        [
            *cell("PROJECT MANAGER",
                  rfi.project.project_manager.name if rfi.project.project_manager else "—"),
            *cell("DATE RECEIVED",   _fmt_date(rfi.received_date)),
            *cell("DATE DUE",        _fmt_date(rfi.due_date)),
            Paragraph("", styles["table_label"]),
            Paragraph("", styles["table_value"]),
        ],
    ]

    col_w = doc.width / 8   # 8 sub-columns (label + value × 4)
    details_table = Table(
        details_data,
        colWidths=[col_w * 1.15, col_w * 0.85] * 4,
    )
    details_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), SLATE_BG),
        ("BACKGROUND",    (0, 1), (-1, 1), WHITE),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(details_table)

    # ── ④ Parties ─────────────────────────────────────────────────────────────
    story += _section_header("PARTIES", styles)

    parties_data = [
        [
            Paragraph("DESIGNERS", styles["table_label"]),
            Paragraph(_names(rfi.designers), styles["table_value"]),
        ],
        [
            Paragraph("CONTRACT ADMINISTRATORS", styles["table_label"]),
            Paragraph(_names(rfi.contract_administrators), styles["table_value"]),
        ],
    ]
    parties_table = Table(parties_data, colWidths=["28%", "72%"])
    parties_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), SLATE_BG),
        ("BACKGROUND",    (0, 1), (-1, 1), WHITE),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(parties_table)

    # ── ⑤ References (drawing + spec) — only when at least one is set ─────────
    has_drawing = bool(rfi.drawing_number)
    has_spec    = bool(rfi.spec_section)

    if has_drawing or has_spec:
        story += _section_header("REFERENCES", styles)

        ref_rows = []
        if has_drawing:
            drawing_str = rfi.drawing_number
            if rfi.drawing_revision:
                drawing_str += f"  {rfi.drawing_revision}"
            if rfi.drawing_title:
                drawing_str += f"  —  {rfi.drawing_title}"
            ref_rows.append([
                Paragraph("DRAWING", styles["table_label"]),
                Paragraph(drawing_str, styles["table_value"]),
            ])
        if has_spec:
            spec_str = rfi.spec_section
            if rfi.spec_section_title:
                spec_str += f"  —  {rfi.spec_section_title}"
            ref_rows.append([
                Paragraph("SPECIFICATION", styles["table_label"]),
                Paragraph(spec_str, styles["table_value"]),
            ])

        ref_table = Table(ref_rows, colWidths=["28%", "72%"])
        ref_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (0, -1), SLATE_BG),
            ("BACKGROUND",    (1, 0), (1, -1), WHITE),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(ref_table)

    # ── ⑥ Question ────────────────────────────────────────────────────────────
    if rfi.question:
        story += _section_header("QUESTION", styles)
        story.append(_body_para(rfi.question, styles))

    # ── ⑥ Proposed Solution ───────────────────────────────────────────────────
    if rfi.proposed_solution:
        story += _section_header("PROPOSED SOLUTION", styles)
        story.append(_body_para(rfi.proposed_solution, styles))

    # ── ⑦ Official Response ───────────────────────────────────────────────────
    story += _section_header("OFFICIAL RESPONSE", styles)

    if rfi.official_response:
        # Tinted background block for the response
        response_data = [[_body_para(rfi.official_response, styles)]]
        response_table = Table(response_data, colWidths=[doc.width])
        response_table.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), GREEN_BG),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
            ("ROUNDEDCORNERS", [4]),
        ]))
        story.append(response_table)

        # Responded-by / date line
        responder = rfi.responded_by.name if rfi.responded_by else "—"
        resp_date = _fmt_date(rfi.responded_at)
        story.append(Spacer(1, 4))
        story.append(Paragraph(
            f"Responded by  <b>{responder}</b>  ·  {resp_date}",
            styles["response_meta"],
        ))
    else:
        story.append(Paragraph("No official response recorded.", styles["body_italic"]))

    # ── ⑧ Attachments ─────────────────────────────────────────────────────────
    attachments = list(rfi.attachments.all())
    if attachments:
        story += _section_header(f"ATTACHMENTS  ({len(attachments)})", styles)
        _att_urls = attachment_urls or {}
        for att in attachments:
            size_kb = att.size / 1024
            size_str = (
                f"{size_kb / 1024:.1f} MB" if size_kb >= 1024 else f"{size_kb:.0f} KB"
            )
            flag = "  [response]" if att.is_official_response else ""
            meta = f"   <font color='#6b7280'>({size_str}){flag}</font>"

            file_url = _att_urls.get(att.id)
            if file_url:
                # Render the filename as a clickable hyperlink (indigo colour).
                safe_name = (
                    att.original_filename
                    .replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                )
                markup = f'•  <a href="{file_url}" color="#4338ca"><u>{safe_name}</u></a>{meta}'
                story.append(Paragraph(markup, styles["attachment_link"]))
            else:
                story.append(Paragraph(
                    f"•  {att.original_filename}{meta}",
                    styles["attachment_item"],
                ))

    # ── Build ─────────────────────────────────────────────────────────────────
    footer = _make_footer(generated_on, app_url=app_url)
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    buf.seek(0)
    return buf
