# Generated by Django 4.2.20 on 2025-08-10 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('discipline', models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Structural', 'Structural'), ('Architectural', 'Architectural')], max_length=50)),
                ('role', models.CharField(choices=[('Project Designer', 'Project Designer'), ('Sub Consultant', 'Sub Consultant'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('Contract Administrator', 'Contract Administrator')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-project_number'],
            },
        ),
        migrations.CreateModel(
            name='Rfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(default='M', max_length=10)),
                ('rfi_name', models.CharField(max_length=200)),
                ('rfi_number', models.CharField(max_length=50)),
                ('received_date', models.DateField()),
                ('due_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_rfis', to='rfis.member')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='rfis.project')),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFIs',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Project Designer', 'Project Designer'), ('Sub Consultant', 'Sub Consultant'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('Contract Administrator', 'Contract Administrator')], max_length=50)),
                ('discipline', models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Structural', 'Structural'), ('Architectural', 'Architectural')], max_length=50)),
                ('is_project_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfis.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfis.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='rfis.ProjectMembership', to='rfis.member'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='rfis.member'),
        ),
        migrations.AddConstraint(
            model_name='rfi',
            constraint=models.UniqueConstraint(fields=('project', 'rfi_number'), name='uniq_rfi_per_project'),
        ),
        migrations.AddConstraint(
            model_name='rfi',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('received_date'))), name='due_not_before_received'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'member')},
        ),
    ]
