# Generated by Django 5.1.6 on 2025-02-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('rfi_name', models.CharField(max_length=100)),
                ('rfi_number', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('due_date', models.DateField()),
                ('remarks', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFIs',
                'ordering': ['-received_date'],
            },
        ),
    ]
