# Generated by Django 4.2.20 on 2025-04-15 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('electrical_designers', models.CharField(blank=True, max_length=100)),
                ('mechanical_designers', models.CharField(blank=True, max_length=100)),
                ('contract_administrator', models.CharField(max_length=100)),
                ('contractors', models.EmailField(max_length=100)),
                ('owners', models.CharField(max_length=100)),
                ('subconsultants', models.EmailField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-project_number'],
            },
        ),
        migrations.CreateModel(
            name='Rfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('trade', models.CharField(default='M', max_length=3)),
                ('rfi_name', models.CharField(max_length=100)),
                ('rfi_number', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('received_date', models.DateField()),
                ('due_date', models.DateField()),
                ('remarks', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_rfis', to='rfis.project')),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFIs',
                'ordering': ['-rfi_number'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='rfis',
            field=models.ManyToManyField(blank=True, related_name='projects', to='rfis.rfi'),
        ),
    ]
