# Generated by Django 5.1.6 on 2025-02-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='trade',
            field=models.CharField(default='M', max_length=3),
        ),
    ]
