# Generated by Django 4.2.20 on 2025-08-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Project Designer', 'Project Designer'), ('Sub Consultant', 'Sub Consultant'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('Contract Administrator', 'Contract Administrator'), ('Project Manager', 'Project Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('Project Designer', 'Project Designer'), ('Sub Consultant', 'Sub Consultant'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('Contract Administrator', 'Contract Administrator'), ('Project Manager', 'Project Manager')], max_length=50),
        ),
    ]
