# Generated by Django 5.2.5 on 2026-04-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0002_alter_member_role_alter_projectmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='official_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_rfis', to='rfis.member'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='RfiComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_official_response', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_comments', to='rfis.member')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rfis.rfi')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['rfi', 'created_at'], name='rfis_rficom_rfi_id_0f58bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='RfiReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfi_read_states', to='rfis.member')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='rfis.rfi')),
            ],
            options={
                'indexes': [models.Index(fields=['member', 'rfi'], name='rfis_rfirea_member__322518_idx')],
                'unique_together': {('rfi', 'member')},
            },
        ),
    ]
