# Generated by Django 5.1.6 on 2025-02-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0002_rfi_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfi',
            options={'ordering': ['-rfi_number'], 'verbose_name': 'RFI', 'verbose_name_plural': 'RFIs'},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_manager', models.CharField(max_length=100)),
                ('designers', models.CharField(max_length=100)),
                ('contract_administrator', models.CharField(max_length=100)),
                ('contractors', models.EmailField(max_length=100)),
                ('owners', models.EmailField(max_length=100)),
                ('subconsultants', models.EmailField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('rfis', models.ManyToManyField(related_name='projects', to='rfis.rfi')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-project_number'],
            },
        ),
        migrations.AddField(
            model_name='rfi',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_rfis', to='rfis.project'),
        ),
    ]
