# Generated by Django 5.1.6 on 2025-02-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0003_alter_rfi_options_project_rfi_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='designers',
        ),
        migrations.AddField(
            model_name='project',
            name='electrical_designers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='mechanical_designers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
