# Generated by Django 5.2.5 on 2026-04-24 00:31

import django.db.models.deletion
import rfis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0003_rfi_closed_at_rfi_official_response_rfi_responded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=rfis.models.rfi_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rfis.rfi')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_attachments', to='rfis.member')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['rfi', 'uploaded_at'], name='rfis_rfiatt_rfi_id_3f1fe9_idx')],
            },
        ),
    ]
