# Generated by Django 5.1.6 on 2025-02-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0004_remove_project_designers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owners',
            field=models.CharField(max_length=100),
        ),
    ]
