# Generated by Django 5.1.6 on 2025-02-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0005_alter_project_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rfis',
            field=models.ManyToManyField(blank=True, related_name='projects', to='rfis.rfi'),
        ),
    ]
