# Generated by Django 5.2.5 on 2026-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0005_rename_remarks_add_proposed_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiattachment',
            name='is_official_response',
            field=models.BooleanField(default=False),
        ),
    ]
