# Generated by Django 5.2.5 on 2026-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0007_rfi_designers_contract_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('responded', 'Responded'), ('closed', 'Closed')], default='open', max_length=15),
        ),
    ]
