# Generated by Django 5.2.5 on 2026-05-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0008_rfi_status_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialResponseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('response_number', models.PositiveIntegerField()),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_response_revisions', to='rfis.member')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_revisions', to='rfis.rfi')),
            ],
            options={
                'verbose_name': 'Official Response Revision',
                'verbose_name_plural': 'Official Response Revisions',
                'ordering': ['-response_number'],
            },
        ),
        migrations.AddField(
            model_name='rfiattachment',
            name='response_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='rfis.officialresponserevision'),
        ),
        migrations.CreateModel(
            name='RfiRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('changes', models.JSONField()),
                ('rfi_status_at_revision', models.CharField(max_length=15)),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfi_revisions', to='rfis.member')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='rfis.rfi')),
            ],
            options={
                'verbose_name': 'RFI Revision',
                'verbose_name_plural': 'RFI Revisions',
                'ordering': ['-revision_number'],
            },
        ),
    ]
