# Generated by Django 5.2.5 on 2026-05-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0009_rfi_revision_response_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anticipated_type', models.CharField(choices=[('PCN', 'Project Change Notice'), ('SI', 'Site Instruction'), ('CD', 'Change Directive'), ('CO', 'Change Order'), ('Other', 'Other')], help_text='The type of formal change document the responder expects to issue.', max_length=10)),
                ('issued_type', models.CharField(blank=True, choices=[('PCN', 'Project Change Notice'), ('SI', 'Site Instruction'), ('CD', 'Change Directive'), ('CO', 'Change Order'), ('Other', 'Other')], help_text='The actual type of formal document issued (may differ from anticipated).', max_length=10)),
                ('reference_number', models.CharField(blank=True, help_text='Reference of the issued document, e.g. PCN-007 or SI-012.', max_length=50)),
                ('description', models.TextField(help_text='Why a formal instruction is required and what is being changed.')),
                ('notes', models.TextField(blank=True, help_text='Free-form notes added when the change is issued or cancelled.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_changes', to='rfis.member')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_contract_changes', to='rfis.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_changes', to='rfis.project')),
                ('response_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_changes', to='rfis.officialresponserevision')),
                ('rfi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_changes', to='rfis.rfi')),
            ],
            options={
                'verbose_name': 'Contract Change',
                'verbose_name_plural': 'Contract Changes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'status'], name='rfis_contra_project_499b70_idx'), models.Index(fields=['rfi', 'status'], name='rfis_contra_rfi_id_e92800_idx')],
            },
        ),
    ]
