# Generated by Django 5.2.5 on 2026-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0011_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('project_added', 'Added to project'), ('project_removed', 'Removed from project'), ('rfi_assigned', 'Assigned to RFI'), ('rfi_due_soon', 'RFI due soon')], max_length=50),
        ),
    ]
