# Generated by Django 5.2.5 on 2026-05-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0012_notification_rfi_verbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='drawing_number',
            field=models.CharField(blank=True, help_text='Sheet/drawing number referenced by this RFI, e.g. A-101, E-104.', max_length=50),
        ),
        migrations.AddField(
            model_name='rfi',
            name='drawing_revision',
            field=models.CharField(blank=True, help_text='Drawing revision at the time of the RFI, e.g. Rev B, IFC.', max_length=20),
        ),
        migrations.AddField(
            model_name='rfi',
            name='drawing_title',
            field=models.CharField(blank=True, help_text='Short description of the drawing, e.g. Ground Floor Plan.', max_length=200),
        ),
        migrations.AddField(
            model_name='rfi',
            name='spec_section',
            field=models.CharField(blank=True, help_text='CSI MasterFormat section number, e.g. 03 30 00.', max_length=20),
        ),
        migrations.AddField(
            model_name='rfi',
            name='spec_section_title',
            field=models.CharField(blank=True, help_text='Section title, e.g. Cast-in-Place Concrete.', max_length=200),
        ),
    ]
