# Generated by Django 5.2.5 on 2026-05-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0017_rficommentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications for RFI activity.'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Set when the overdue-escalation management command runs; prevents duplicate escalations.'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='parent_rfi',
            field=models.ForeignKey(blank=True, help_text='Closed RFI that this revision supersedes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rfis', to='rfis.rfi'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='return_note',
            field=models.TextField(blank=True, help_text='Reason provided when the RFI is returned to the submitter.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('project_added', 'Added to project'), ('project_removed', 'Removed from project'), ('rfi_assigned', 'Assigned to RFI'), ('rfi_due_soon', 'RFI due soon'), ('mentioned', 'Mentioned in comment'), ('rfi_returned', 'RFI returned to submitter'), ('official_response', 'Official response submitted'), ('rfi_status_change', 'RFI status changed'), ('watcher_activity', 'RFI activity (watching)'), ('rfi_overdue', 'RFI overdue'), ('rfi_comment', 'New comment on RFI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('responded', 'Responded'), ('returned', 'Returned to Submitter'), ('closed', 'Closed')], default='open', max_length=15),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='rfis.member')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='rfis.rfi')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RfiWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_rfis', to='rfis.member')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='rfis.rfi')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('rfi', 'member')},
            },
        ),
    ]
