# Generated by Django 5.2.5 on 2026-04-30 02:31

import django.db.models.deletion
import email_ingestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfis', '0007_rfi_designers_contract_administrators'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Friendly name, e.g. "RFI Inbox"', max_length=100)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365'), ('other', 'Other (custom host)')], default='gmail', max_length=20)),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=200)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('username', models.EmailField(help_text='The email address to log in with', max_length=254)),
                ('password', models.CharField(help_text='App password (Gmail) or account password', max_length=500)),
                ('mailbox', models.CharField(default='INBOX', help_text='IMAP folder to watch, e.g. "INBOX" or "RFIs"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_create_threshold', models.FloatField(default=0.85, help_text='Confidence score (0–1) above which an RFI is created automatically')),
            ],
            options={
                'verbose_name': 'Email Config',
                'verbose_name_plural': 'Email Configs',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=500, unique=True)),
                ('received_at', models.DateTimeField(help_text='Date/time the email was sent (from headers)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When our poller picked it up')),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0, help_text='Project-match confidence score (0–1)')),
                ('match_reason', models.CharField(blank=True, help_text='Human-readable explanation of how the project was matched', max_length=300)),
                ('parsed_rfi_name', models.CharField(blank=True, max_length=200)),
                ('parsed_question', models.TextField(blank=True)),
                ('parsed_trade', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('auto_created', 'Auto-created RFI'), ('approved', 'Manually Approved'), ('rejected', 'Rejected'), ('error', 'Processing Error')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('email_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='email_ingestion.emailconfig')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='rfis.project')),
                ('rfi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_email', to='rfis.rfi')),
            ],
            options={
                'verbose_name': 'Inbound Email',
                'verbose_name_plural': 'Inbound Emails',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=email_ingestion.models.email_attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('inbound_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_ingestion.inboundemail')),
            ],
            options={
                'ordering': ['original_filename'],
            },
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['status', '-received_at'], name='email_inges_status_ef9f8a_idx'),
        ),
    ]
