# Generated by Django 5.2.5 on 2026-04-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='gmail_primary_only',
            field=models.BooleanField(default=True, help_text='Gmail only — fetch emails from the Primary tab only, ignoring Promotions, Social, and Updates.'),
        ),
    ]
